---

- name: install docker-ce dependencies
  package:
    name: '{{ docker_package_dependencies }}'
    state: present

- name: configure docker-ce apt key
  apt_key:
    url: '{{ docker_apt_key }}'
    state: present
  when: ansible_os_family == 'Debian'

- name: configure docker-ce apt repository
  apt_repository:
    filename: docker-ce
    repo: 'deb [arch=amd64] {{ docker_apt_url }} {{ ansible_distribution_release }} stable'
    state: present
  when: ansible_os_family == 'Debian'

- name: install docker-ce
  package:
    name: '{{ docker_packages }}'
    state: present

- name: add cleanup cronjob
  cron:
    name: Docker Cleanup
    minute: '{{ docker_cleanup_cronjob_minute }}'
    hour: '{{ docker_cleanup_cronjob_hour }}'
    day: '{{ docker_cleanup_cronjob_day }}'
    month: '{{ docker_cleanup_cronjob_month }}'
    weekday: '{{ docker_cleanup_cronjob_weekday }}'
    job: docker system prune -af
  when: docker_cleanup_cronjob_enable
