---
name: CI - Release

on:
  release:
    types: [created, edited, published, released]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: galaxy
        uses: robertdebock/galaxy-action@1.0.1
        with:
          galaxy_api_key: ${{ secrets.galaxy_api_key }}
